<Project Sdk="LibreWPF.Sdk/0.1.0-preview.41">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>$(ProGpuWpfSdkSampleTargetFramework)</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LeXtudio.DevFlow.Agent.LibreWpf" Version="0.2.2" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets/MvpResource.txt" />
    <Content Include="Assets/MvpContent.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>Assets/MvpContent.txt</TargetPath>
    </Content>
  </ItemGroup>
</Project>
