<Project Sdk="LibreWPF.Sdk/11.0.0-dev">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>$(ProGpuWpfSdkSampleTargetFramework)</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.1.2" />
  </ItemGroup>
</Project>
