<Project>

  <PropertyGroup>
    <_ProGpuWpfSdkImported>true</_ProGpuWpfSdkImported>
    <UseWPF Condition="'$(UseWPF)' == ''">true</UseWPF>
    <ImportFrameworkWinFXTargets Condition="'$(ImportFrameworkWinFXTargets)' == ''">false</ImportFrameworkWinFXTargets>
    <ProGpuWpfUsePortablePlatform Condition="'$(ProGpuWpfUsePortablePlatform)' == ''">true</ProGpuWpfUsePortablePlatform>
    <ProGpuWpfPlatform Condition="'$(ProGpuWpfPlatform)' == ''">SilkNet</ProGpuWpfPlatform>
    <ProGpuWpfRenderingBackend Condition="'$(ProGpuWpfRenderingBackend)' == ''">ProGPU</ProGpuWpfRenderingBackend>
    <ProGpuWpfSdkVersion Condition="'$(ProGpuWpfSdkVersion)' == ''">0.1.0-dev</ProGpuWpfSdkVersion>
    <ProGpuWpfReferenceMode Condition="'$(ProGpuWpfReferenceMode)' == ''">Package</ProGpuWpfReferenceMode>
    <ProGpuWpfPackageVersion Condition="'$(ProGpuWpfPackageVersion)' == ''">$(ProGpuWpfSdkVersion)</ProGpuWpfPackageVersion>
    <ProGpuPackageVersion Condition="'$(ProGpuPackageVersion)' == ''">$(ProGpuWpfSdkVersion)</ProGpuPackageVersion>
  </PropertyGroup>

  <Import Sdk="Microsoft.NET.Sdk.WindowsDesktop" Project="Sdk.props" />
  <Import Project="$(MSBuildThisFileDirectory)..\targets\ProGPU.Wpf.Sdk.props" />

</Project>
